services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: oidc_auth
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
